f(try: g() catch err: err)
